#!/usr/bin/env python

REQ = 99
REPLY = 100
DEFAULT = 0
REQUEST_PROXY = 1
REQUEST_ADD_DEVICE_TO_PROXY = 2
REQUEST_REMOVE_DEVICE_FROM_PROXY = 3
REQUEST_AVAILABLE_DEVICES_LIST = 4
REPLY_PROXY_ID = 5
REPLY_DEVICE_ADDED_TO_PROXY = 6
REPLY_REMOVED_DEVICE_FROM_PROXY = 7
REPLY_AVAILABLE_DEVICES_LIST = 8
ERROR = 10
EXCEPTION = 11